### ISSUE TITLE
APIError(code=-4006): Stop price less than zero

### ISSUE THREAD

**Issue by anam-cara** [sammchardy/python-binance#1093]
**Describe the bug**
I am currently developing a tradingbot which listens to webhooks and places future trades based on said webhook input. So far so good, I was already able to place the first trades. For the sake of simplicity, I started with basic market orders. In a next step, I want to include stop loss with my order.

My solution currently throws me an error from the Binance API and I can't find the source of the issue:
"an exception occured - APIError(code=-4006): Stop price less than zero."

**To Reproduce**
For the sake of simplicity, I hardcoded the function input the below example. In reality, I derive the stop price based on mark price, leverage and buy/sell side and store it as a float.

client.futures_create_order(symbol='BTCUSDT', side='BUY', type='STOP_MARKET', quantity=0.001, stop_price=59553.27495, isolated='TRUE')

**Expected behavior**
Code places market order with a stop loss

**Environment (please complete the following information):**
 - Python version: 3.7.9
 - Virtual Env: venv
 - OS: Windows 10 Pro
 - python-binance version

**Logs or Additional context**

**Comment by anam-cara** [comment]
I might have just found the solution to my issue. Binance handles Stop Losses and Take Profits as separate orders, thus, in order to create e.g. a buy order with a stop loss, you have to create a regular buy order and create a separate sell order at the desired stop loss price

[](https://github.com/jaggedsoft/node-binance-api/issues/614)

**Comment by ctu1121** [comment]
Hi

> [anam-cara](/anam-cara)

Hi anam-cara,
I have bought ETCUSDT future position at price 30, I try to set  price 20 as stop sell order in order to protect my account.
While I run below code:

binance_client.futures_create_order(
      symbol='ETCUSDT',
      type='STOP',
      timeInForce='GTC',  
      price='20',  
      side= 'SELL',        
)

I saw the error message as below from Anaconda Spyder(Python3.9):

BinanceAPIException: APIError(code=-4006): Stop price less than zero.

May I have your advice? Thank you.

Charles

**Comment by jobsuccess** [comment]
Even I'm also facing the same issue, is there any update on the query...Kindly share !!

**Comment by ksern94** [comment]
> Hi
> 
> > [anam-cara](/anam-cara)
> 
> Hi anam-cara, I have bought ETCUSDT future position at price 30, I try to set price 20 as stop sell order in order to protect my account. While I run below code:
> 
> binance_client.futures_create_order( symbol='ETCUSDT', type='STOP', timeInForce='GTC', price='20', side= 'SELL', )
> 
> I saw the error message as below from Anaconda Spyder(Python3.9):
> 
> BinanceAPIException: APIError(code=-4006): Stop price less than zero.
> 
> May I have your advice? Thank you.
> 
> Charles

For future peeps landing here. I'm not using this python package but I had this same error because I forgot to set the stopPrice when issuing a stop order.

https://binance-docs.github.io/apidocs/futures/en/#new-order-trade
stopPrice - Used with STOP/STOP_MARKET or TAKE_PROFIT/TAKE_PROFIT_MARKET orders.
