### ISSUE TITLE
how to keep Web Socket Streams alive

### ISSUE THREAD

**Issue by NomanSu** [sammchardy/python-binance#122]
binance-official-api-docs says :
A single connection to stream.binance.com is only valid for 24 hours; expect to be disconnected at the 24 hour mark.
how to keep stream connection alive in code? Do the connecting again after 24hours?

**Comment by SkylerX** [comment]
Hi @NomanSu , try to put it in a loop with a time function , there are few standard libraries already in python. Cheers

**Comment by NomanSu** [comment]
@SkylerX  i didn't find this infos in depthCache.py, can you show me?

**Comment by SkylerX** [comment]
@NomanSu you won't find this in depthCache.py, you can find it in standard python library, to give you an example, you could:
import time
time.sleep(60)
and put it inside of a while True loop.
There are many other way, you can google it.
Hope this helped.
Cheers

**Comment by sammchardy** [comment]
Hi @NomanSu the websockets should heal themselves on disconnects, have you seen otherwise?

The python-binance library attempts 5 reconnects on a disconnect, increasing time between each time. If it fails to reconnect you will get an error message on your call back function. See the documentation here https://python-binance.readthedocs.io/en/latest/websockets.html#websocket-errors

**Comment by NomanSu** [comment]
@sammchardy  How and when do you know your  websockets is disconnected?   Or python library WebSocketClientFactory  controls this?

**Comment by jeanfcari** [comment]
Hi @sammchardy , first of all thanks for the amazing package and documentation. I am having a problem with the public websockets being disconnected. I think the problem is coming from Binance's side since disconnections usually coincide with this website showing peaks in reports: https://istheservicedown.com/problems/binance. 

Wouldn't it be suitable to add, for say, a factor=10 variable to the BinanceReconnectingClientFactory? If I understand correctly, binance being down for 0.1*5=0.5 seconds will make it impossible to ever reconnect?
