### ISSUE TITLE
Breaking change in 1.0.23

### ISSUE THREAD

**Issue by tsunamilx** [sammchardy/python-binance#1508]
Appreciated the work really, but 1.0.23 moved all websocket classes to a new folder "ws", which breaks the existing code, although it is easy to fix, this kind of change should be marked as breaking change and must be highlighted in the changelog

**Comment by pcriadoperez** [comment]
Hi @tsunamilx,

Thanks for your feedback, and apologies for the inconvenience. We assumed this wouldn’t be a breaking change since the main classes remain accessible via the library index, but we understand how it might have impacted your workflow. We'll ensure such changes are clearly marked as breaking in the changelog going forward.

Appreciate your comment!
