### ISSUE TITLE
Error (ImportError: No module named '_strptime') when running program packaged by pyinstaller or cx-Freeze

### ISSUE THREAD

**Issue by wattwei** [sammchardy/python-binance#220]
Traceback (most recent call last):
  File "C:\Python36-32\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
    module.run()
  File "C:\Python36-32\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
    exec(code, m.__dict__)
  File "main.py", line 2, in <module>
  File "C:\binance\mainWindow.py", line 7, in <module>
    from worker import Worker
  File "C:\binance\worker.py", line 6, in <module>
    from binance.client import Client, BinanceAPIException
  File "C:\Python36-32\lib\site-packages\binance\client.py", line 8, in <module>
    from .helpers import date_to_milliseconds, interval_to_milliseconds
  File "C:\Python36-32\lib\site-packages\binance\helpers.py", line 3, in <module>
    import dateparser
  File "C:\Python36-32\lib\site-packages\dateparser\__init__.py", line 4, in <module>
    from .date import DateDataParser
  File "C:\Python36-32\lib\site-packages\dateparser\date.py", line 13, in <module>
    from dateparser.date_parser import date_parser
  File "C:\Python36-32\lib\site-packages\dateparser\date_parser.py", line 11, in <module>
    from .parser import parse
  File "C:\Python36-32\lib\site-packages\dateparser\parser.py", line 10, in <module>
    from dateparser.utils.strptime import strptime
  File "C:\Python36-32\lib\site-packages\dateparser\utils\strptime.py", line 55, in <module>
    __strptime = patch_strptime()
  File "C:\Python36-32\lib\site-packages\dateparser\utils\strptime.py", line 26, in patch_strptime
    'strptime_patched', *imp.find_module('_strptime')
  File "C:\Python36-32\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_strptime'

**Comment by copex91** [comment]
Hi, coud you fix this?

**Comment by alberand** [comment]
Is there a workaround or patch to fix it?
I have the same problem. Windows, python3.6, python-binance 0.6.8

**Comment by copex91** [comment]
I am also building a little app with python-binance and this seems to fix _strptime error, but throws others missing dependencies.
```
build_exe_options = {
    "include_files":["<your_path_to_python>/Python36/Lib/_strptime.py"]
}
```

**Comment by michaelgooode** [comment]
I also have this issue when running pyinstaller

**Comment by copex91** [comment]
its working for me with cx_freeze and this setup.py

```
import sys
import zope, google
from cx_Freeze import setup, Executable

# Dependencies are automatically detected, but it might need fine tuning.
build_exe_options = {
    "include_files":["<your_path_to_python>/Python36/Lib/_strptime.py",
                     "<your_path_to_certificate>/cert.json"],
    "namespace_packages": ["zope.interface", "google"],
    "packages": ["os", "idna", "_cffi_backend"],
    "excludes": ["tkinter"]}
setup(  name = "binance",
        version = "0.1",
        description = "binance",
        options = {"build_exe": build_exe_options},
        executables = [Executable("<your_main_file>.py")])
```

**Comment by wattwei** [comment]
the issue moved there

https://github.com/pyinstaller/pyinstaller/issues/3429

https://github.com/pyinstaller/pyinstaller/issues/3430

**Comment by Alvesxvii** [comment]
> 

Dude.. I'm having such a hard time to setup it.... Your answer was the best in order to compile it with cxfreeze. It won't give me that _strptime error anymore once its including it to the root path of the application.
Thing is that when I run my .exe, it opens the CMD so quickly that I can't see anything.. like if there's some kind of error. Or maybe it isn't opening the prompt, but just executing as if it is in second layer... I can't really determine what's going on... 

I'm sure it is executing my script because I added a keys.ini file in the path of my program to store my api_key and api_secret from Binance. When I manage to leave one of those empty in keys.ini, the app raises an exeption saying: Signature for this request is not valid. I have function inside my program that calls the status of my account. So it basically means that when I determine that a variable is equals to client.get_account(), it can't find that status because of wrong api and secret keys provided. What I'm trying to say is that this error shows its everything okay with my code. 
I think the prompt is probably not opening because of some config in setup.py. I'm using basically same information as yours, but I dind't pass "<your_path_to_certificate>/cert.json" in the dictionary... I was wondering what was that for... but couldn't find it even googling it. So I don't know if this could be the reason my prompt isnt prompting... 

I'll let my code here both Binance_API.py (dealing with the api) and my setup.py 

---------------------------------- Binance_API.py ------------------------------------------------

from configparser import ConfigParser
from binance.client import Client
from binance.enums import *
import time
import os


chaves_ini = ConfigParser()

caminho_chaves_ini = r'chaves.ini'

chaves_ini.read(caminho_chaves_ini, encoding='UTF8')

api_key = chaves_ini.get('CHAVES', 'api_key')
api_secret = chaves_ini.get('CHAVES', 'api_secret')


if api_key == '' or api_secret == '':

    print('Arquivo de configuração de chaves preenchido incorretamente ou algum dos valores encontra-se em branco.')
    print('Encerrando em: 5s')
    time.sleep(1)

    print('Encerrando em: 4s')
    time.sleep(1)

    print('Encerrando em: 3s')
    time.sleep(1)

    print('Encerrando em: 2s')
    time.sleep(1)

    print('Encerrando em: 1s')
    time.sleep(1)
    # exit()

elif api_key != '' or api_secret != '':
    print('Chaves registradas com sucesso!')
    time.sleep(1)


client = Client(api_key, api_secret)

checando_status = client.get_account_status()

status = checando_status.get('data')


try:
    if status == 'Normal':
        print('')
        print('A conexão com a API foi estabelecida com sucesso!')
except ValueError:
    print('Impossível conectar-se. Houve um erro com a api_secret fornecida, ou com o IP permitido.')


print('')
detalhes = client.get_account()

#for dado in detalhes:

#    print(dado)



def MostraSaldos():

    print('')
    ativos = detalhes['balances']

    for ativo in ativos:
        nome = ativo['asset']
        quantidade = ativo['free']

        if float(ativo['free']) > 0:

            print(f'Ativo: {nome} - {quantidade}')

    print('')


MostraSaldos()

def Criar_ordem_mercado():
    print('')
    print('#ATENÇÃO: O ticker inicial é a referência!')
    print('#Exemplo: BNBBTC - Compra: Comprará BNB usando BTC / Venda: Venderá BNB ganhando BTC')
    print('#Exemplo: BTCBNB - Compra: Comprará BTC usando BNB / Venda: Venderá BTC ganhando BNB')
    print('')
    time.sleep(0.5)
    par = input(str('-> Digite o par de negociação: '))
    print('')
    operacao = input(int('-> Deseja comprar ou vender? - Digite: 1- Comprar / 2- Vender : '))
    print('')
    quantidade = input(int('-> Digite a quantidade a ser comprada/vendida: '))
    print('')

    if operacao == 1:

        ordem_compra = client.create_order(
            symbol=par,
            side=SIDE_BUY,
            type=ORDER_TYPE_MARKET,
            #timeInForce=TIME_IN_FORCE_GTC,
            #price='0.00001',
            quantity=quantidade)

        tipo_ordem_executado = ordem_compra['type']
        lado_executado = ordem_compra['side']
        status_executado = ordem_compra['status']
        par_executado = ordem_compra['symbol']
        id_ordem_executado = ordem_compra['orderId']
        qtd_executado = ordem_compra['executedQty']
        ativo_comissao_executado = ordem_compra['commissionAsset']
        comissao_executado = ordem_compra['commission']

        print(f'Par: {par_executado} - Status: {status_executado} - Tipo de ordem: {tipo_ordem_executado} - Lado: {lado_executado}')
        print(f'ID Ordem: {id_ordem_executado} - QTD Operada: {qtd_executado}')
        print(f'Ativo utilizado para pagar comissão da transação: {ativo_comissao_executado}')
        print(f'Valor da comissão: {comissao_executado}{ativo_comissao_executado}')


    elif operacao == 2:

        ordem_venda = client.create_order(
            symbol=par,
            side=SIDE_SELL,
            type=ORDER_TYPE_MARKET,
            #timeInForce=TIME_IN_FORCE_GTC,
            #price='0.00001',
            quantity=quantidade)

        tipo_ordem_executado = ordem_venda['type']
        lado_executado = ordem_venda['side']
        status_executado = ordem_venda['status']
        par_executado = ordem_venda['symbol']
        id_ordem_executado = ordem_venda['orderId']
        qtd_executado = ordem_venda['executedQty']
        ativo_comissao_executado = ordem_venda['commissionAsset']
        comissao_executado = ordem_venda['commission']

        print(f'Par: {par_executado} - Status: {status_executado} - Tipo de ordem: {tipo_ordem_executado} - Lado: {lado_executado}')
        print(f'ID Ordem: {id_ordem_executado} - QTD Operada: {qtd_executado}')
        print(f'Ativo utilizado para pagar comissão da transação: {ativo_comissao_executado}')
        print(f'Valor da comissão: {comissao_executado}{ativo_comissao_executado}')

----------------------------------- setup.py ------------------------------------------

import sys
from cx_Freeze import setup, Executable

# Dependencies are automatically detected, but it might need fine tuning.
build_exe_options = {"include_files": ["C:/Users/marli/AppData/Local/Programs/Python/Python39/Lib/_strptime.py"],
                     "packages": ["os", "configparser", "binance", "binance.client", "binance.enums"],
                     "includes": ["configparser", "binance", "binance.client", "binance.enums", "time"],
                     "excludes": ["tkinter"]}

# GUI applications require a different base on Windows (the default is for
# a console application).
base = None
if sys.platform == "win32":
    base = "Win32GUI"

setup(
    name="Binance API",
    version="0.1",
    description="Gestão de carteira Binance automatizada",
    options={"build_exe": build_exe_options},
    executables=[Executable("Binance_API.py", base=base)]
)
