### ISSUE TITLE
ResourceWarning: unclosed socket.socket

### ISSUE THREAD

**Issue by luizfzs** [sammchardy/python-binance#231]
I am seeing `ResourceWarning: unclosed <socket.socket fd=5, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('xxxx.xxxx.xxxx.xxxx', 55970), raddr=('54.65.243.34', 443)>`
 when unit testing a function that calls `client.get_symbol_ticker()` and I cannot find the appropriate function to close it. Is the intentional behaviour to leave it open?

**Comment by sammchardy** [comment]
Hi @luizfzs, this is not really an error per se, as it's listed as a warning.

Internally python-binance uses requests' Session class which has a keep-alive so that subsequent requests are faster.

There is a related discussion on the requests library
https://github.com/requests/requests/issues/3912

You can explicitly close the session like this.

```
from binance.client import Client 

client = Client("<api_key>", "<api_secret">)

# do something

# explicitly close the session
client.session.close()
```
