### ISSUE TITLE
Event time is outside open/close time for 1m Candlesticks

### ISSUE THREAD

**Issue by kstamos-code** [sammchardy/python-binance#237]
Hi,

I am opening a websocket for ETHBTC to get 1m candlesticks using the python api. 
I notice that pretty frequently I get messages where the event time is after the the close time of the bar,
It seems that there is some form of lag maybe? Should I ignore it and carry on?.
What I am trying to achieve is to have 1m candlesticks as building blocks for any possible interval. However, occasionally there are small mismatches between live-gathered candlesticks aggregated from 1m to  3m.  and historical 3m klines.  Can I put the blame on this delay? 

>utcnow 2018-04-05 14:08:00.404732
utc_event_time 2018-04-05 14:08:00.265000
utc_start_time_of_this_bar 2018-04-05 14:07:00.000000
utc_close_time_of_this_bar 2018-04-05 14:07:59.999000

**Comment by gdm-willgu** [comment]
by definition, the `event_time` is later than the `close_time` -- you'd need to pass that `close_time` point in order to generate the 1m bar event.

For the mismatches, none of us would be able to know the details of implementation on Binance's side. However, one plausible explanation is that their `1m` bar and `3m` bar are different components, meaning that although they receive the same set of data, the arriving time of data might be slightly different.

If I have to guess, it happens more often that the `open` or `close` differs between your `3m` bar and Binance historical `3m bar`, rather than `high` and `low`. But if that's not the case, then I might be barking up the wrong tree.
