### ISSUE TITLE
I need get_orderbook_tickers() but for just one ticker

### ISSUE THREAD

**Issue by lucasart** [sammchardy/python-binance#289]
I'm trying to convert balances (of various coins) into BTC. For this I need bid/ask (to compute mid) of `XXX/BTC` pair for any coin `XXX`.

I looked at the documentation, but could not find a better way than:
* loading the entire universe of currency pairs `XXX/YYY`, with bid/ask using `get_orderbook_tickers()`
* looping through all of them, until I find the `XXX/BTC` that I was looking for

This is incredibly clumsy and inelegant. It would be nice to have a function that just returns the bid/ask of a single symbol. Or, even better, a function that directly converts from one coin to another.

**Comment by darkblank** [comment]
Hi there.
I hope you understand I'm not good at English.
I think you can use this function, `client.get_order_book(symbol='BNBBTC')`.
This function return order book for just one symbol.
(Maybe you can check what really return is, trying to use this function.)
It maybe return symbol,asks list,bids list.
You need to do bring best price of these list(lowest price of asks list, highest price of bids list)
because this function not gives you just first price of bid and ask like function `get_orderbook_tickers()`

**Comment by lucasart** [comment]
thanks. both solutions work.
