### ISSUE TITLE
Get_historical_klines doesn't show full set of data

### ISSUE THREAD

**Issue by MirkoZulj** [sammchardy/python-binance#298]
Hi,

I wanted to use get_historical_klines to pull information for past 4 hours (1 minute intervals), but I get data for the interval t-4h to t-2h. I can't see information for past 2 hrs. Do you know what is the cause of this?
Is there something else you would recommend to see information for past 4 hrs in 1 min intervals?

**Comment by jmcnab57** [comment]
@MirkoZulj You don't have to use the `get_historical_klines()` to do this. You can just use the `get_klines()`. The `get_klines()` function will return the most recent klines up to the limit. Documentation says 500 klines but I think Binance raised the amount to 1000 (that's how many im currently getting). You only need to set the limit to 240 klines (60 * 4) since you only want 1 minute tickers for 4 hours.`client.get_klines(symbol=coin,interval=client.KLINE_INTERVAL_1MINUTE,limit=240)`

If you want to use the historical version please provide how you are setting your start_time. Note if doing get historical you don't need to set the end time so that it grabs up to the current time.

**Comment by MirkoZulj** [comment]
I have tried:
output =client.get_klines(symbol="VENETH", interval = Client.KLINE_INTERVAL_1MINUTE, limit=500, startTime=1529920688678, endTime=1529924288683)
And got empty array. If I go beyond 2 hrs it works without problem, but doesn't show last two hours
I get_historical_klines, the loop would stop because len(temp_data) = 0, so the loop breaks.

**Comment by MirkoZulj** [comment]
If I remove startTime and endTime and just put limit to 240, then I get data for t-6hr to t-2hr

**Comment by MirkoZulj** [comment]
I found the error. In the start time I asked for "4 hours ago" and in End time I selected "Now UTC". As I am UTC+2, it gave me data for 2 hours only
