### ISSUE TITLE
Is 1 second the fastes way to pull data from Binance?

### ISSUE THREAD

**Issue by MauriPastorini** [sammchardy/python-binance#324]
First I start pulling data of tickets with API request, and I reach the 1200 per minute. 
Then I thought of the web sockets, but I found that they deliver the information with 1 second frequency. So, How is the fastest way to pull data from binance?

Thank you

**Comment by wranai** [comment]
This is probs better asked on the @binance_api_english telegram channel.

**Comment by anson-vandoren** [comment]
@MauriPastorini it depends on what you're trying to accomplish. If you just want to pull a bunch of historical data (klines, for example), you can get fastest data through the REST API, since you can pull `(1000 klines per request) * (1200 requests per minute) == 20,000 klines per second` (if your internet connection supports that, and if you process requests in parallel. The websocket connection for kline data, by contrast, is only going to give you a new data point each 1 minute (at the fastest). 

If you're looking for trade (or aggregate trade) data, you will get them in realtime over the websocket connection, but no way to get previous trades through the websocket, since that's not what they're for.

So really just depends on whether you are trying to get realtime data (use websockets), or historical data (use the REST API).

Hope that helps.

**Comment by MauriPastorini** [comment]
Hello! Thank you for your response! Yes I need the bid and ask in real time, as fast as we can. We are using the websockets, but it seems that even with that they push new data no faster than 1 second. Or that is what we understood

**Comment by fmanrique96** [comment]
> Hello! Thank you for your response! Yes I need the bid and ask in real time, as fast as we can. We are using the websockets, but it seems that even with that they push new data no faster than 1 second. Or that is what we understood

Were you able to figure this out?

**Comment by MauriPastorini** [comment]
@fmanrique96 No, I have to live with retrieving the data every second, no less

**Comment by pablobendiksen** [comment]
As of September 2019 Binance has implemented faster websocket orderbook data response: from 1000 ms to 100 ms. Hope this helps.

https://www.binance.com/en/support/articles/360032916632

**Comment by jasongoodwin** [comment]
Yeah I'm using 100ms orderbook updates via ws now. But you should know that other exchanges have faster information updates than binance does if you want faster data. 
Some example code in rust over here for retrieving, merging, and sorting orderbooks from different exchanges via ws, and publishing them for grpc clients. Very fast - sub ms internal processing. 

Hope it helps as an example project. Note the timeouts - because the network stack can take some time to propagate a partition, the timeouts are set per exchange. https://github.com/jasongoodwin/orderbooks-rs
