### ISSUE TITLE
Can’t even run the first line.

### ISSUE THREAD

**Issue by grahmani** [sammchardy/python-binance#345]
Hey 👋 
I’m new in this. I like to write a simple robot but I can’t even run the first line.
Pip install python-binance
I tried to install pip and python-binance from file=>settings=>project:pycharmprojects=>project interpreter
Then clicking on add and search and install both pip and python-binance.
But this line isn’t running again.
Then tried to install the twist file for pyrhon version 3.7 as in that video. It was installed, but this line isn’t running again. I don’t know what to do.
Please if you know how to start to do this, just let me know.
I’m using win10 64bit. Thank you.

**Comment by youstanzr** [comment]
did you import python-binance to your project?

**Comment by CJ1976** [comment]
I commented on another user's post that's having trouble getting started. I use Anaconda and it installs everything automatically. I have never ran into cryptic errors like that when running Anaconda. I use Spyder because I like the layout of the environment but there is one or two other development environments that come packaged with Anaconda. I don't know if you had to compile and install libs yourself or not, but you might have installed something incorrectly or you might have a version conflict or any of a bunch of other possibilities. I would install Anaconda first and make sure your underlying system is solid before I started suspecting the binance modules.

**Comment by anson-vandoren** [comment]
```console
$ pip install python-binance
```
is a command to run from your console (Command Prompt or Powershell on Windows) to install this library. If you are using PyCharm, and have added the package using Project Interpreter settings page, you've already got it installed (that page does basically the same thing as the command above, but through the PyCharm GUI instead)

Either way, this is not a line you should include in your python script.
