### ISSUE TITLE
Order Function - How do i get the API response?

### ISSUE THREAD

**Issue by PythonNewbie101** [sammchardy/python-binance#359]
Hello!

I'm pretty new to all this so sorry for the (hopefully!) simple question. 

When i submit a test order, everything completes as expected. I added on the arg:newOrderRespType so i can ensure the order was processed, but i don't know how to get that response? All i see is that the program completes without error...

Any help would be hugely appreciated. 

This is what i have for the function:

order = client.create_test_order(
    symbol='BNBBTC',
    side=Client.SIDE_BUY,
    type=Client.ORDER_TYPE_LIMIT,
    timeInForce=TIME_IN_FORCE_GTC,
    quantity='50',
    price='100',
    newClientOrderId='12354843511',
    newOrderRespType='FULL')

I've tried print(order)
as well as:

order2=order
print(order2)
print(create_test_order(newOrderRespType))

but to no avail...

Thanks in advance for the time!

**Comment by anson-vandoren** [comment]
@PythonNewbie101 creating a test order returns an empty response by design if the order would be valid (see [the official docs](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#test-new-order-trade)). You would get an error in the response if there were a problem with it, so the fact that your response is empty means success.

Without more information, I'm not sure what you're expecting instead. If you were just hoping for some sort of "success!" response, then it looks like you got that (empty response). If you were looking for something different, perhaps you're looking for a different method instead.

Happy to help further if needed, if you provide some more information about what you're expecting.

Regards,
Anson
