### ISSUE TITLE
Multiple websockets for multiple Binance accounts

### ISSUE THREAD

**Issue by joshuar87** [sammchardy/python-binance#388]
Hi there,

I would like to add friends accounts to my bot. They will have their own API and secret keys though. Is it possible to open up more than one socket with different keys? Channels? Or do you need to run separate python instances?

Much appreciate any opinion in this regard.

Thanks

**Comment by gaboesquivel** [comment]
Hi @joshuar87 I believe you can accomplish that with this lib https://github.com/unicorn-data-analysis/unicorn-binance-websocket-api

**Comment by Mar1h** [comment]
Hi @joshuar87 !
Did you manage to find a way to do it ? I am actually implementing something similar and having an issue closing sockets I am not interested in anymore ... And if I can't close sockets I won't be able to manage the data from multiple accounts :/
@gaboesquivel Unicorn Data seems interesting but a bit young to build upon or do you have previous experience using it yourself ?

**Comment by bithon** [comment]
Hi Mar1h!
I am the maintainer of unicorn-binance-websocket-api and i would like to provide you an answer to your question.
I wrote the API, because we had the need of an improved one compared to existing solutions. Since yesturday (version 1.2.2) everything i wanted to code is coded (code coverage 100%). And it has a lot of nice functions that will you help you managing your streams. For me it was important, that the coder starts a stream and everything else is done by the api, so you dont have to "manage" anything else. The documentation is completed, there are example files for every case  - just download and start them. I am still testing to find and remove all bugs, but actualy its very stable on my systems.
![Screenshot_20190428_101359](https://user-images.githubusercontent.com/47597331/56861367-5861d080-69a0-11e9-81d9-21cc6f7f912b.png)

If you are interessted, i think its the best you download it and test it - i would be happy to get your feedback!

**Comment by saurabhrb** [comment]
I was able to overcome this by running the asyncio loop forever
[https://github.com/saurabhrb/python-binance/commit/743dabe0d8534be1a2f9cd1297bae6d8b54443cd](url)
