### ISSUE TITLE
Question: Should the DepthCache be cleared when init_cache is called?

### ISSUE THREAD

**Issue by Jonzky** [sammchardy/python-binance#418]
I noticed a bug where over a long period of time incorrect an incorrect ask remained in the DepthCache - effectively invalidating the whole data collected. I'm not too sure what caused the initial incorrect DepthCache entry, but I assumed the refresh_interval would hard reset the DepthCache ensuring it is synced with binance.

From what I can see the DepthCache is initialised when the DepthCacheManager is created and never cleared during the refresh_intervals.

The issue is if the price is drifting and a stale entry remains in the DepthCache, then the invalid data will remain indefinitely.

I haven't raised this as a bug as I'm not sure if I'm missing something, or if its been done like this for another reason - but it would make sense to me to clear the DepthCache when init_cache is called.

**Comment by henboss** [comment]
I just came across this myself.. not sure if it is exactly what you are describing but it seems like when init_cache is called on the refresh, the bids and asks go out of sync- I am assuming because the depth cache isn't cleared and so is retaining old bids and asks. Not sure why this hasn't been fixed @sammchardy ?
