### ISSUE TITLE
Keep-alive a listenKey for User Data Streams

### ISSUE THREAD

**Issue by JosephWN** [sammchardy/python-binance#455]
**Describe the bug**
Binance updated their system a few days ago, now the user account WS stream need ping lisenKey to keep a live every 30 minitues. In current version v0.7.4 I found the user account stream dropped every 1-2 hours, I guess the reason maybe we need ping lisenKey every 30 minitues.

Please see the docs here: https://github.com/binance-exchange/binance-official-api-docs/blob/master/user-data-stream.md

**Expected behavior**
Implementation for Keep-alive a listenKey for User Data Streams.

**Environment (please complete the following information):**
 - Python version: 3.6
 - Virtual Env: [e.g. virtualenv, conda]
 - OS: Ubuntu
 - python-binance version 0.7.4

**Comment by oliver-zehentleitner** [comment]
Hi Joseph!

Pinging the listenkey is a requirement since the first day, its not new.

It seems there is a bug and there are already 2 pull requests that aim to fix this bug:
https://github.com/sammchardy/python-binance/pull/440
https://github.com/sammchardy/python-binance/pull/433

So you can wait till one of this PRs get merged or you use the one of the forks (repo of the pull requests).

And there is an other solution you can use, I wrote a binance websocket lib for python that handles all reconnects autocratically and that offers a few more benefits:
https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api

best regards,
Oliver
