### ISSUE TITLE
ModuleNotFoundError: No module named 'binance.client'; 'binance' is not a package

### ISSUE THREAD

**Issue by kevinapetrei** [sammchardy/python-binance#477]
from binance.client import Client
ModuleNotFoundError: No module named 'binance.client'; 'binance' is not a package

I've just done: pip install python-binance.

please help!

**Comment by oliver-zehentleitner** [comment]
Maybe you have python2 and python3 on your system?

PIP has installed python-binance for python2 and your script runs with python3?

try `python3 -m pip install python-binance` and take care your script runs with python3 too!

**Comment by Flowelcat** [comment]
Same here, python3.6 not working

**Comment by nikhil-kankarla** [comment]
If you're running the import statement from within a file called binance.py, [this](https://github.com/sammchardy/python-binance/issues/72) will be relevant for you

**Comment by grantbelford** [comment]
Dear all,
fyi. I was able to solve this problem by adding Binance Folder path to environment variables:
1. Environment Variables: add 
     PYTHONPATH
     C:\Users\user\Anaconda3\Lib\site-packages\binance;     (add a semi-colon at the end)
2. Restart JupyterNB
3 .  If you run following in JupyterNB you should see the above path added.
        import sys
        sys.path
Reference: https://www.youtube.com/watch?v=A7E18apPQJs&feature=youtu.be

**Comment by janascc** [comment]
Hi all
being able to install the below fixed the issue I had with **_No module named 'binance.client'; 'binance' is not a package_**
!pip install C:\\Users\\<your user name>\\Downloads\\Twisted-20.3.0-cp39-cp39-win_amd64.whl

.whl source file downloaded from here https://www.lfd.uci.edu/~gohlke/pythonlibs/#twisted

**Comment by ThySpecter** [comment]
Is this solved?

**Comment by Flowelcat** [comment]
> If you're running the import statement from within a file called binance.py, [this](https://github.com/sammchardy/python-binance/issues/72) will be relevant for you

Check this answer, if you have package or file named "binance" this error may occur.

**Comment by kuratkull** [comment]
from binance.websockets import BinanceSocketManager
ModuleNotFoundError: No module named 'binance.websockets'

why am i getting such an error. I did all the setup steps I just get an error on binance.websockets

**Comment by campbellkerr** [comment]
Yep, I realised I had a file binance.py in the same directory - after renaming that all good!

**Comment by sibdib** [comment]
I have this nad I installed everything correctly: 
Traceback (most recent call last):
 ```
 File "D:\Trading\news-analysis.py", line 39, in <module>
    from binance.websockets import BinanceSocketManager
ModuleNotFoundError: No module named 'binance.websockets'
```

**Comment by mohammadizaan** [comment]
I tried a lot of things already here on google but nothing was useful, then I tired pip install python-binance==0.7.5 instead of pip install python-binance==0.7.9, and I was successful to import " from binance.client import Client. 

Beside this, I also renamed my two binance.py files as binance.client.py, and it worked for me.

You can find your binance.py files in your python3 site packages folder. Just go there and search binance.py, you will find it.

That's all what I did successfully.

If it is helpful for you , so kindly leave a comment.

**Comment by victorkingi** [comment]
Here is something stupid I forgot to do. If you are using Jupyter notebook and Conda environments, make sure the kernel selected is the conda environment having the packages installed, otherwise, it will use the default system python which doesn't have any packages.

After opening a notebook, go to `Kernel` then `change kernel` 
![image](https://user-images.githubusercontent.com/65971651/126033120-4bc2d9c2-2258-41ce-bc72-5e4841f66d6e.png)

If your conda environment isn't listed, follow this steps:
1. Run `conda install -c anaconda ipykernel` . You might need to run as administrator in windows 10/11
2. Run `python -m ipykernel install --user --name=firstEnv` where `firstEnv` is your environment name.
3. Restart jupyter notebook and you should now have a new kernel under change kernel with your conda env name.

Cheers! :)

**Comment by k8p8sz** [comment]
From me the solution was simple:
somehow there was a binance.py file in the site-packages folder, I just renamed it to something else, and restarted kernel.

...\Anaconda3\envs\"name of your your env"\lib\site-packages\**binance.py**

**Comment by swiftwuz** [comment]
> If you're running the import statement from within a file called binance.py, [this](https://github.com/sammchardy/python-binance/issues/72) will be relevant for you

this saved my life thank you

**Comment by hurleyhan888** [comment]
A very simple fix for me...just make sure your python code _IS NOT saved in a file called binance.py_...i renamed mine and it worked smoothly, seems the module requires that filename and that creates some conflict.  Hope this helps

**Comment by mrhouzlane** [comment]
It is not working work me is this import deprecated ? 

I found this : from binance import Client, ThreadedWebsocketManager, ThreadedDepthCacheManager

**Comment by FedericoMurtula** [comment]
> > ```
> > from binance.client import Client
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ModuleNotFoundError: No module named 'binance.client'; 'binance' is not a package
> > I've just done: pip install python-binance.
> > please help!
> 
> I just changed the value "include-system-site-packages" in the file pyvenv.cfg of my project from "false" to "true", and everything worked.

it worked after tried a lot of things. Thanks !!

**Comment by topereacts** [comment]
i cant still find a solution after trying all these

**Comment by coolmib** [comment]
> i cant still find a solution after trying all these

Try : from binance.streams import BinanceSocketManager

**Comment by mailsonpuc** [comment]
O nome do arquivo.py que você criou não pode se binance, mude para outro nome que funciona.
