### ISSUE TITLE
Should I use this repo or one of the forks?

### ISSUE THREAD

**Issue by p-i-** [sammchardy/python-binance#478]
I notice there are 807 forks to this repo.

Looking at `Insights -> Contributors`, it seems this repository is actively maintained.

Am I best off working from this repository, or are any of the forks noteworthy?

This is a general problem with starting on any open source project with multiple forks. I wish GitHub would display the number of commits in each fork when I list the forks. Otherwise there is no easy way to see how much effort has been put into various forks.

**Comment by oliver-zehentleitner** [comment]
If you take a look at https://github.com/sammchardy/python-binance/network you can see there are only 70-80 forks listed, i belief thats because all the other forks dont have additional commits.

Some of the forks are trying to make something different, removed some dependencies or added some special things and some of them are merged with the main repo. You can observe this with the colored lines.

**Comment by am11y** [comment]
Hello Oliver, as I found you here I would like to ask you for help. If I use your unicorn-binance-websocket-api together with sammchardy's python-binance, then I get ImportError:

site-packages\unicorn_binance_websocket_api\unicorn_binance_websocket_api_connection.py", line 36, in <module>
    from websockets import connect
ImportError: cannot import name 'connect' from 'websockets' 

Please help, I can only get both running by removing sammchardy's library from Python PATH before calling imports:
sys.path.remove(pytonInstallFolder + "\\Python38\\Lib\\site-packages\\binance")
