### ISSUE TITLE
use 100ms depth cache

### ISSUE THREAD

**Issue by OpenCoderX** [sammchardy/python-binance#487]
Looks like binance now allows 100ms depth cache updates, how can I configure this parameter?

**Comment by frozenranger** [comment]
Yup I can confirm this as well. The fix is very easy: In the function 'start_depth_socket' in websockets.py, simply scroll down and find the line '169' with ' socket_name = symbol.lower() + '@depth' and change it to
  
socket_name = symbol.lower() + '@depth@100ms' # updated for 100ms

now you get 100ms response time :) 

@OpenCoderX

**Comment by OpenCoderX** [comment]
I ended up using my private fork with the patch from #492 , it would be nice to use the @sammchardy fork.

**Comment by kimchirichie** [comment]
closing in favor of #492
