### ISSUE TITLE
Impossible to Sell on Binance :  APIError(code=-1106): Parameter 'quantity' sent when not required.

### ISSUE THREAD

**Issue by samixchoumi** [sammchardy/python-binance#488]
Hello

When i try to sell ETH to USDT i've this error : 
[-] Impossible to Sell on Binance :  APIError(code=-1106): Parameter 'quantity' sent when not required.

My quantity_token =: 0.001003

The problem is that quantity is required so, why i've this error ?

**Comment by xiaods** [comment]
@samixchoumi please paste your sample code, I feel your code is not correct.

**Comment by Stuffman** [comment]
> @samixchoumi please paste your sample code, I feel your code is not correct.

I'd like to enter dialogue too. My error is almost the same:

binance.exceptions.BinanceAPIException: APIError(code=-1106): Parameter 'quantity' sent when not required.

The code is:

balance = float(client.get_asset_balance(asset='USDT')['free'])
divide = round(balance / float(depth2['asks'][0][0]), 6)
qtoorder = 0
if divide > (balance / float(depth2['asks'][0][0])):
    qtoorder = round(divide - 0.000001,6)
else:
    qtoorder = round(divide,6)
client.order_market_buy(symbol='BTCUSDT', quantity=qtoorder)

Well, I take the balance and calculate which maximum quantity I can buy due to step_size. It works always, but suddenly very strange error turned out. I don't even imagine how parameter 'quantity' can be not required in opening position...
Help me please!

**Comment by Stuffman** [comment]
I think the problem is that you have 6 digital signes, when traded quantity of ETH is max 3 signs. So you should sell 0.001 ETH, not 0.001003
