### ISSUE TITLE
about volume 

### ISSUE THREAD

**Issue by alperasan** [sammchardy/python-binance#493]
hi there i have got a little question about volume. how can we separate volume about buy volume and sell volume ?

**Comment by lupsa** [comment]
search on google for: `base asset and quote asset`

**Comment by KevinMBS** [comment]
Hello, I believe you were wrong with your question, the volume cannot be separated in the buy and the sell because both are equal, in order to have a buy order completed, a sell order must be completed as well, and both orders correspond at the same volume, so after all the buy volume will be the same as the sell volume
