### ISSUE TITLE
Create Market close position on Futures API

### ISSUE THREAD

**Issue by chaudoe** [sammchardy/python-binance#536]
Anyone have idea on how we can create Market close position order on Futures market? I tried this one as a close order for a Short trade by pass in all required params and one `closePosition ` param then called this function
```
def placeBuyOrder():
            orderBuy = Binance.client.futures_create_order(
                symbol= self.symbol,
                side= 'BUY',
                type= 'MARKET',
                closePosition= 'true'
                )
```

but in return are these exceptions

```
File "C:\Users\chaum\AppData\Local\Programs\Python\Python38\lib\site-packages\binance\client.py", line 3584, in futures_create_order
    return self._request_futures_api('post', 'order', True, data=params)
  File "C:\Users\chaum\AppData\Local\Programs\Python\Python38\lib\site-packages\binance\client.py", line 222, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "C:\Users\chaum\AppData\Local\Programs\Python\Python38\lib\site-packages\binance\client.py", line 197, in _request
    return self._handle_response()
  File "C:\Users\chaum\AppData\Local\Programs\Python\Python38\lib\site-packages\binance\client.py", line 230, in _handle_response
    raise BinanceAPIException(self.response)
  File "C:\Users\chaum\AppData\Local\Programs\Python\Python38\lib\site-packages\binance\exceptions.py", line 13, in __init__
    self.code = json_res['code']
KeyError: 'code'
```

Is it means my function have problems or this is wrapper side problem?

**Comment by sloth456** [comment]
Hi @chaudoe 

If for example you have a short order worth 1 BTC.  To close this you must place a long order of 1 BTC.

The issue in your code is that you have specified closePosition parameter on a MARKET order, closePosition is only used with STOP_MARKET or TAKE_PROFIT_MARKET.  Also, since you are using a MARKET order you must also specify the quantity.

To close a short order worth 1 BTC you would need the following code:

`Binance.futures_create_order(symbol=self.symbol, side='BUY', type='MARKET', quantity=1, reduceOnly='true')`

I added reduceOnly parameter to prevent a BUY order being placed if there is no short position already in Binance.  

If you do not know the exact quantity of the original position, you can also close the order by using an inflated value for quantity, for BTCUSDT you could use a value of 100 to close any shorts with a value below that.

Alternatively you may also try setting a STOP_MARKET order which would close the position once a particular price has been crossed.  This does not require a quantity to be specified if you use the 'closePosition' parameter.

For example

`Binance.futures_create_order(symbol=self.symbol, side=BUY, type='STOP_MARKET', stopPrice=stop_price, closePosition='true')`

That last example is untested, but I believe it should work

**Comment by chaudoe** [comment]
Thank you sloth456, it worked, I dont think it could be this simple. I think I tried that before but my quantity was converted to float so it might be rounded up somewhere so it didn't worked

**Comment by kretxo** [comment]
Hello,

That works fine for me for Market orders. But I'm having issues to create stop_loss and take-profit  LIMIT orders.

I can create LIMIT orders without any issue as follows:
client.futures_create_order(symbol=symbol, side='BUY', type='LIMIT', timeInForce='GTC', quantity=quantity, price=price)

But I don't know how to create take_profit and stop_loss LIMIT orders. I tried different things, but I always get errors. Could you please help me on that?

Thanks.

**Comment by kretxo** [comment]
Ah, it's now solved. I was missing parematers.
Thanks,

**Comment by chaudoe** [comment]
> I can create LIMIT orders without any issue as follows:
> client.futures_create_order(symbol=symbol, side='BUY', type='LIMIT', timeInForce='GTC', quantity=quantity, price=price)

I think you should use 'STOP_LOSS_LIMIT' and 'TAKE_PROFIT_LIMIT' in type parameter like this 
`client.futures_create_order(symbol=symbol, side='BUY', type='TAKE_PROFIT_LIMIT', timeInForce='GTC', quantity=quantity, price=price)`

`client.futures_create_order(symbol=symbol, side='BUY', type='STOP_LOSS_LIMIT', timeInForce='GTC', quantity=quantity, price=price)`

or included `reduceOnly='true'` like sloth456 mentioned above because your orders likely to be misunderstood as new long/short order, in that case I recommend you to look for cancel futures orders function in the wrapper to clear out all stop loss order after the price hit take profit

**Comment by avatar-lavventura** [comment]
> symbol=self.symbol, side=BUY, type='STOP_MARKET', stopPrice=stop_price, closePosition='true'

I keep having `*** binance.exceptions.BinanceAPIException: APIError(code=-4061): Order's position side does not match user's setting.` when I try bot sides.

```
BUY = client.SIDE_BUY
SELL = client.SIDE_SELL

client.futures_create_order(symbol=_symbol, side=BUY, type='STOP_MARKET', stopPrice=80.0,
closePosition='true')
```

**Comment by sloth456** [comment]
@avatar-lavventura without looking too deeply - just a hunch but is your account set in Hedge mode? You may need to set it to one way mode to get it working.

Check this link, different project but someone else having same error on binance api.

https://github.com/jaggedsoft/node-binance-api/issues/411

**Comment by avatar-lavventura** [comment]
@sloth456 Yes my account was in hedge-mode. I will give it a try with the one way mode

**Comment by majidnow** [comment]
> Ah, it's now solved. I was missing parematers.
> Thanks,

Hi @kretxo 
How did you solve the problem of create stop_limit order in futures account?
I did create entry order by this:
client.futures_create_order(
            symbol=order.symbol
            side= Client.SIDE_BUY ,
            type = Client.ORDER_TYPE_LIMIT,
            timeInForce=Client.TIME_IN_FORCE_GTC,
            quantity=order.quantity,
            price=order.price)

and it's worked, but I can't create stop loss order. My request is :

client.futures_create_order(
          symbol=order.symbol,
          side= Client.SIDE_SELL,
          type = Client.ORDER_TYPE_STOP_LOSS_LIMIT,
          timeInForce=Client.TIME_IN_FORCE_GTC,
          quantity=order.quantity,
          stopPrice=order.stop,
          price=order.stop)
and I got 'invalid orderType' error.

Any suggestion?

**Comment by sloth456** [comment]
@majidnow kretxo was doing LIMIT orders not stop limit orders. 

In regards to stop limit orders, when I read the official binance futures API docs:

https://binance-docs.github.io/apidocs/futures/en/#new-order-trade

I see that 'STOP_LOSS_LIMIT' isn't a thing.  Looks like it's just named 'STOP' for a limit stop and 'STOP_MARKET' for a stop market. I haven't checked but it looks like you might need to do:

```
client.futures_create_order(
symbol=order.symbol,
side= Client.SIDE_SELL,
type = 'STOP',
timeInForce=Client.TIME_IN_FORCE_GTC,
quantity=order.quantity,
stopPrice=order.stop,
price=order.stop)
```

Looks like the constant defined in this module are incorrect or maybe just got outdated.  See line 56 in Client.py

```
ORDER_TYPE_STOP_LOSS = 'STOP_LOSS'
ORDER_TYPE_STOP_LOSS_LIMIT = 'STOP_LOSS_LIMIT'
```

**Comment by FabioNgo** [comment]
Hi everyone,
The api is good now, but i face an issue that i cannot close the position immediately, some time the stop price never matched. Sometimes it raised "order is immediately execution" exception. How can we close position like press the "market" button on the binance app?
Thank you,

**Comment by barkntuncer** [comment]
> > I can create LIMIT orders without any issue as follows:
> > client.futures_create_order(symbol=symbol, side='BUY', type='LIMIT', timeInForce='GTC', quantity=quantity, price=price)
> 
> I think you should use 'STOP_LOSS_LIMIT' and 'TAKE_PROFIT_LIMIT' in type parameter like this
> `client.futures_create_order(symbol=symbol, side='BUY', type='TAKE_PROFIT_LIMIT', timeInForce='GTC', quantity=quantity, price=price)`
> 
> `client.futures_create_order(symbol=symbol, side='BUY', type='STOP_LOSS_LIMIT', timeInForce='GTC', quantity=quantity, price=price)`
> 
> or included `reduceOnly='true'` like sloth456 mentioned above because your orders likely to be misunderstood as new long/short order, in that case I recommend you to look for cancel futures orders function in the wrapper to clear out all stop loss order after the price hit take profit

Do we have to define two orders to achieve stop loss together with take profit? Also, with the latest notation for 'STOP' we do need 2 prices namely stopPrice and price. I checked the documentation but couldn't find the difference between them. Can somebody explain to me?

**Comment by JPizzal** [comment]
I'm looking to code in python a FUTURES TAKE PROFIT LIMIT ORDER at the LAST PRICE with the TAKE PROFIT at the LAST PRICE. For some reason I'm only seeing the ability to do hedging which is two separate orders in order to have a take profit. When my code opens a long or short it simply isn't registering the take profit and it sits open but it separately opens a take profit market order at the take profit price and never actually buys in. [](url)
<img width="1069" alt="Screen Shot 2021-07-08 at 3 45 23 AM" src="https://user-images.githubusercontent.com/86794449/124953532-198d2380-dfca-11eb-9bdb-11d7f68664b7.png">
<img width="1046" alt="Screen Shot 2021-07-08 at 3 55 52 AM" src="https://user-images.githubusercontent.com/86794449/124953544-1c881400-dfca-11eb-8dd8-f4cfaebd3bc5.png">
<img width="677" alt="Screen Shot 2021-07-08 at 8 12 23 AM" src="https://user-images.githubusercontent.com/86794449/124953550-1db94100-dfca-11eb-8e20-77ee41afab2f.png">

**Comment by JPizzal** [comment]
> Hi @chaudoe
> 
> If for example you have a short order worth 1 BTC. To close this you must place a long order of 1 BTC.
> 
> The issue in your code is that you have specified closePosition parameter on a MARKET order, closePosition is only used with STOP_MARKET or TAKE_PROFIT_MARKET. Also, since you are using a MARKET order you must also specify the quantity.
> 
> To close a short order worth 1 BTC you would need the following code:
> 
> `Binance.futures_create_order(symbol=self.symbol, side='BUY', type='MARKET', quantity=1, reduceOnly='true')`
> 
> I added reduceOnly parameter to prevent a BUY order being placed if there is no short position already in Binance.
> 
> If you do not know the exact quantity of the original position, you can also close the order by using an inflated value for quantity, for BTCUSDT you could use a value of 100 to close any shorts with a value below that.
> 
> Alternatively you may also try setting a STOP_MARKET order which would close the position once a particular price has been crossed. This does not require a quantity to be specified if you use the 'closePosition' parameter.
> 
> For example
> 
> `Binance.futures_create_order(symbol=self.symbol, side=BUY, type='STOP_MARKET', stopPrice=stop_price, closePosition='true')`
> 
> That last example is untested, but I believe it should work

I'm looking to code in python a FUTURES TAKE PROFIT LIMIT ORDER at the LAST PRICE with the TAKE PROFIT at the LAST PRICE. For some reason I'm only seeing the ability to do hedging which is two separate orders in order to have a take profit. When my code opens a long or short it simply isn't registering the take profit and it sits open but it separately opens a take profit market order at the take profit price and never actually buys in.

**Comment by wuzzy1212** [comment]
Why can't you just closeposition=true on a market order with no stop loss, you can close the position on the app no issues you don't need to place a reverse trade. its ridiculous to not have an easy kickout mechanism. binance api is a joke

**Comment by sloth456** [comment]
> Why can't you just closeposition=true on a market order with no stop loss, you can close the position on the app no issues you don't need to place a reverse trade. its ridiculous to not have an easy kickout mechanism. binance api is a joke

It is certainly something you'd expect would be simple in the API.  Since you mentioned closing positions within the app itself I was curious and decided to inspect chrome logs when clicking close via market.  I can see that binance does nothing special or any different to what is discussed in this thread, binance's own app simply closes by placing a MARKET order for the same BTC qty as the open position, I noticed that the side parameter was set to 'BOTH' and reduceOnly set to 'true'.  This might make closing easier if you don't know whether a position is long or short.

I was also curious what binance is doing when you click 'close all positions'.  For this, they are in fact doing something different, it doesn't look like they have documented in their API

They're using api endpoint

https://www.binance.com/bapi/futures/v2/private/future/order/clear-position

With the following payload

![image](https://user-images.githubusercontent.com/1080709/146469306-93dbc37b-030d-4b19-8373-b656708bd0be.png)

This could potentially be a way to close out a position if you have only one.  I have not tested this, it's also not something that this module has support for so you'd have to do a custom post to this endpoint to see if you can get it working, or perhaps you can request for support to be added to this module.

**Comment by wuzzy1212** [comment]
Hah, I guess I can't get angry about it if they are literally using the same calls to close the position.  Thanks for that note, appreciate it.

**Comment by julio899** [comment]
> Hi @chaudoe
> 
> If for example you have a short order worth 1 BTC. To close this you must place a long order of 1 BTC.
> 
> The issue in your code is that you have specified closePosition parameter on a MARKET order, closePosition is only used with STOP_MARKET or TAKE_PROFIT_MARKET. Also, since you are using a MARKET order you must also specify the quantity.
> 
> To close a short order worth 1 BTC you would need the following code:
> 
> `Binance.futures_create_order(symbol=self.symbol, side='BUY', type='MARKET', quantity=1, reduceOnly='true')`
> 
> I added reduceOnly parameter to prevent a BUY order being placed if there is no short position already in Binance.
> 
> If you do not know the exact quantity of the original position, you can also close the order by using an inflated value for quantity, for BTCUSDT you could use a value of 100 to close any shorts with a value below that.
> 
> Alternatively you may also try setting a STOP_MARKET order which would close the position once a particular price has been crossed. This does not require a quantity to be specified if you use the 'closePosition' parameter.
> 
> For example
> 
> `Binance.futures_create_order(symbol=self.symbol, side=BUY, type='STOP_MARKET', stopPrice=stop_price, closePosition='true')`
> 
> That last example is untested, but I believe it should work

## Thanks so much

**Comment by vhjjm** [comment]
How to place a future order with take profit and stop loss plz reply here

**Comment by kirwa444** [comment]
Any one with notes on limit and market orders  on binance API, in hedge mode , i am just confused with conflicting information online

**Comment by arsh-charlesriver** [comment]
Please help - I am going crazy trying to place a limit order for the partial closure of the open position.  
I keep getting **"APIError (code=-1022): Signature for this request is not valid."** error. 
I have a short position on ETHYSDT and I want to place an order that takes profit from1/3 od the position at a certain price:

order_confirmation = binance_client.futures_create_order(
            symbol="ETHUSDT",
            side="BUY",
            type=binance_client.FUTURE_ORDER_TYPE_STOP_MARKET, # on this one I already tried everything out there
            quantity='0.014',
            timeInForce="GTC",
            reduceOnly="true",
            closePosition='false', 
            price='1512.12',
            stopPrice='1512.12',
            recvWindow=600000,
            timestamp=timestamp
            )
I tired many different combinations and solutions I could find on the web. There is no problem with signature / api_key or secret_key because other type of orders (e.g. limit orders to open new positions) work fine with the same code. What could be the issue here?

**Comment by sloth456** [comment]
Hi @arsh-charlesriver 

It's been a long time since I used this module but I'll give it a go and see if I can help.

What I noticed is that you defined the timestamp and the recvWindow, with this module you shouldn't need to specify those in your requests, I believe the module already adds them, this might mess with the signature since you are defining them for a 2nd time.  Also the error you get is to do with the signature, so it is my hunch that perhaps these are the problem.

You said you wanted to place a LIMIT 'buy' to partially close, I'd simplify the whole thing down to this

```
order_confirmation = binance_client.futures_create_order(
  symbol="ETHUSDT",
  side="BUY",
  type="LIMIT"
  quantity="0.014",
  timeInForce="GTC",
  reduceOnly="true",
  price="1512.12"
)
```

Notice I've removed the type constant you where trying to use and just used "LIMIT" as per binance documentation.  If you want to stick to constants, I think the one this module has defined is binance_client.ORDER_TYPE_LIMIT - personally I've always just preferred to manually define the type, but it's just a preference

I've removed the timestamp and recvWindow parameters, it's my suspicion these might be the issue, I've never needed to define them using this module.

Finally, since this is a LIMIT order I've removed the stopPrice and closePosition parameters as they're not needed for this order type.

I hope I have helped, it's a really long time since I used this module.  Might also be worth noting that binance seems to have it's own official python binance SDK now, located here

https://github.com/binance/binance-futures-connector-python

It is probably more up to date, if you're still having issues, might be worth using that instead.

**Comment by ChangoBuitrago** [comment]
> > Why can't you just closeposition=true on a market order with no stop loss, you can close the position on the app no issues you don't need to place a reverse trade. its ridiculous to not have an easy kickout mechanism. binance api is a joke
> 
> It is certainly something you'd expect would be simple in the API. Since you mentioned closing positions within the app itself I was curious and decided to inspect chrome logs when clicking close via market. I can see that binance does nothing special or any different to what is discussed in this thread, binance's own app simply closes by placing a MARKET order for the same BTC qty as the open position, I noticed that the side parameter was set to 'BOTH' and reduceOnly set to 'true'. This might make closing easier if you don't know whether a position is long or short.
> 
> I was also curious what binance is doing when you click 'close all positions'. For this, they are in fact doing something different, it doesn't look like they have documented in their API
> 
> They're using api endpoint
> 
> https://www.binance.com/bapi/futures/v2/private/future/order/clear-position
> 
> With the following payload
> 
> ![image](https://user-images.githubusercontent.com/1080709/146469306-93dbc37b-030d-4b19-8373-b656708bd0be.png)
> 
> This could potentially be a way to close out a position if you have only one. I have not tested this, it's also not something that this module has support for so you'd have to do a custom post to this endpoint to see if you can get it working, or perhaps you can request for support to be added to this module.

I tested out. You will get a 403. Cheers.
