### ISSUE TITLE
Threads: binance.exceptions.BinanceAPIException: APIError(code=-1003): Way too many requests; IP banned

### ISSUE THREAD

**Issue by leexxg** [sammchardy/python-binance#54]
I got class with 3 api methods that i call into it:
Common code
```
"""
client = Client(api_key, api_secret) # CALL ONCE
while True:
   sleep(random.randint(5,10)
   ticker = client.get_ticker(symbol='{}{}'.format(markets[0],markets[1]))
   sleep(1)
   orderbook = client.get_order_book(symbol='{}{}'.format(markets[0],markets[1]),limit=1000)
   sleep(1)
   history = client.get_historical_trades(symbol='{}{}'.format(markets[0],markets[1]),limit=500)
"""
```
**When i use threads(threading.Thread)**, untill it's less than 3 - all OK. But when it's 3 and more i got 
_binance.exceptions.BinanceAPIException: APIError(code=-1003): Way too many requests; IP banned until TimeStamp_

_From documentation:
At the current time Binance rate limits are:
1200 requests per minute
10 orders per second (what mean orders in my case?)
100,000 orders per 24hrs_

**Is it actual information? 
Cause, as i thought, i made 9 requests total (max - 3 methods in 3 threads) at one second(if all random-time sets at one value), and i still got that error. Or it counts not like that? In what moment i get over 1200?**

Also i read here https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#limits 
and here - https://github.com/binance-exchange/binance-official-api-docs/blob/master/errors.md#-1003-too_many_requests in official documentation.

**Still don't understand where i get over limits  for my 3 calls (get_ticker, get_order_book, get_historical_trades)? And what max. possible limits for that methods?**

**Comment by sammchardy** [comment]
Hi @leexxg, the rate limits are based on information from the `get_exchange_info()` call, you can see the current rate limits there.
Note that some calls have higher weight than others, especially if you're fetching for many symbols at once. Check the official docs for more info https://github.com/binance-exchange/binance-official-api-docs
Otherwise I'd enable debugging on requests and see what is actually sent.
Then hit up the Binance API Telegram group for official support for your issue. https://t.me/binance_api_english
