### ISSUE TITLE
binance.exceptions.BinanceAPIException: APIError(code=-1021)

### ISSUE THREAD

**Issue by arthurlirui** [sammchardy/python-binance#60]
When I using market order API, it will return the 
raise BinanceAPIException(response)
binance.exceptions.BinanceAPIException: APIError(code=-1021): Timestamp for this request is outside of the recvWindow.
The related source code is: 
 order = client.order_market_sell(symbol=symbol, quantity=unit, recvWindow=10000)
But when I change the code by changing recvWindow=10000 to recvWindow=100000, the problem solved.
So, what's the main meaning of recvWindow? I set to 100000 means the network delay could be 100 seconds. but I think 10 seconds is enough for an average delay of most of the internet environment.

**Comment by sammchardy** [comment]
@arthurlirui make sure your local time is synced with an internet time server to avoid the Timestamp error. I wouldn't recommend changing the recvWindow to fix an issue caused by your time being out of sync.
You can read more about the recvWindow parameter at the official docs https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#timing-security
