### ISSUE TITLE
TypeError: start_aggtrade_socket() missing 1 required positional argument: 'callback'

### ISSUE THREAD

**Issue by gundamoof** [sammchardy/python-binance#85]
Hi I'm getting this error 
Traceback (most recent call last):
  File "D:\Binance\Test\test.py", line 30, in <module>
    bm.start_aggtrade_socket(symbol='BNBBTC')
TypeError: start_aggtrade_socket() missing 1 required positional argument: 'callback'  
I'm new to python. Any solution on this?

**Comment by willguxy** [comment]
@gundamoof It's pretty much language agnostic. You'd need to define a callback function so that the module knows what to do when receiving a message/payload through the socket. According to [the doc](http://python-binance.readthedocs.io/en/latest/websockets.html), one such example would be the following:

```
def process_message(msg):
    print("message type: {}".format(msg['e']))
    print(msg)
    # do something
```

The `msg` is the python dictionary with fields defined in the [Binance API doc](https://www.binance.com/restapipub.html#wss-endpoint)

**Comment by sammchardy** [comment]
Hi @gundamoof sorry the README example was incorrect. The start_aggtrade_socket function requires the symbol and a callback function as parameters.

The documentation is updated to reflect this now.
