### ISSUE TITLE
CPU spikes and possible memory leak

### ISSUE THREAD

**Issue by LordOberlord** [sammchardy/python-binance#882]
Hello,

i am currently using the ThreadedWebsocketManager in Python and calling for 100 symbols:
`twm.start_symbol_book_ticker_socket(callback=self.req.handle_socket_message,symbol=symbol)`
The response output is saved in a Numpy Array, old data gets an update, so its not getting any bigger.

Later I noticed lagspikes in my CPU usage. After assign CPU 0 to my script I get the following picture:
![Unbenannt](https://user-images.githubusercontent.com/61432991/119951947-cb353f80-bf9c-11eb-9588-5e16167e3e65.PNG)

Every time a lagspike occurred the Memory usage increased by few Kilobytes. After 24 hours the memory usage doubled and CPU 0 was pinned at 100%.

I hope someone can help with the problem. After debugging I am almost certain something is wrong inside the Websocket Manager that cant be resolved by me.

Sincerely Max

**Comment by sammchardy** [comment]
This has been fixed in v1.0.11

For real-time streams some messages may be dropped, especially the `!bookTicker` which streams thousands of messages per second. A queue was implemented internally which when full discards messages until the client can catch up.

If you're after just a particular symbol book ticker then I would suggest using `ethbtc@bookTicker` instead of the above code.

For other types of streams that aren't real-time then a normal function should be able to keep up.

**Comment by LordOberlord** [comment]
The upgrade to v1.0.11 indeed fixed the behavior.

I owe you.

**Comment by ttamg** [comment]
Was having the same problem on v 1.0.10.  Thanks for the fix.  I will do the upgrade now.

**Comment by sniffski** [comment]
Hey guys I'm using 1.0.15 and seem to have same problem which should have been fixed after 1.0.11...
I'm only subscribing two symbols and not sure exactly how to debug to find out where is the issue... What I've managed to find out is memory increases with ~100mb every 5 minutes... So far as a workaround I'm restarting the script everytime it hits 4.5gigs of RAM, but I'm pretty sure there must be smarter way to overcome this issue :(
Please help!

**Comment by masimo12358** [comment]
I'm seeing the same issue in 1.0.16. Memory increase over time until OOM.
