### ISSUE TITLE
 code bug? in depth cache add_bid and add_ask methods

### ISSUE THREAD

**Issue by NomanSu** [sammchardy/python-binance#99]
this is your code,
self._bids[bid[0]] = float(bid[1])
if bid[1] == "0.00000000":
        del self._bids[bid[0]]
why do u add key and value in the map firstly then delete it in case of value is zero? it is always deleting successfully.
in my work, i found bit of missing when deleting, is there something wrong with missing? how the missing orders hanppend? thx.

**Comment by sammchardy** [comment]
Hi @NomanSu the main case for doing it like that is in the case where `bid[0]` is unknown to us, so just blindly deleting would cause an error. That's why in the code it inserts it, so we know the entry is there and then removes it.
Alternative you could use an `if bid[0] in self._bids` but the above is more efficient.

I'm not sure what you mean by  

> in my work, i found bit of missing when deleting, is there something wrong with missing? how the missing orders hanppend?

Are you able to give an example of this?

**Comment by NomanSu** [comment]
Hi, thanks for reply.
why bid[0] is unknown to us? isn't this bid/ask exists in our local orderbook and its volume now is zero?

**Comment by sammchardy** [comment]
When we initialise the order book snapshot we get to a depth of 500, bid and asks can be added or removed outside this range.

**Comment by NomanSu** [comment]
oops.
Yes this is one case. Is there other cases where in 1000ms bid/ask orders placed and then they were cancelled or eaten up so these orders' volumes shifted to zero?

**Comment by sammchardy** [comment]
@NomanSu that could be a possibility. I haven't observed the responses that closely to understand if that actually occurs.

**Comment by NomanSu** [comment]
Understood.
thank you.
